protected/modules/admin/controllers/CategoryController.php
<?/*******************************************************************************************************************
* This file is the part of "DropShop" taobao(c) showcase project http://dropshop.pro
* Copyright (C) 2013 - 2014 DanVit Labs http://danvit.net
* All rights reserved and protected by law. Certificate #40514-UA 21.12.2013
* You can't use this file without of the author's permission.
* ====================================================================================================================
* <description file="CategoryController.php">
* </description>
**********************************************************************************************************************/?>
<?php

class CategoryController extends CustomAdminController {
  public $defaultAction = 'admin';

  /**
   * Displays a particular model.
   * @param integer $id the ID of the model to be displayed
   */
  public function actionView($id) {
    $this->renderPartial('view', array(
      'model' => $this->loadModel($id),
    ), FALSE, TRUE);
  }

  /**
   * Creates a new model.
   * If creation is successful, the browser will be redirected to the 'view' page.
   */
  public function actionCreate() {
    $model = new Category;

    // Uncomment the following line if AJAX validation is needed
    // $this->performAjaxValidation($model);

    if (isset($_POST['Category'])) {
      $model->attributes = $_POST['Category'];
      if ($model->save()) {
        echo Yii::t('admin', "Запись сохранена");
      }
    }
    else {
      $this->renderPartial('create', array(
        'model' => $model,
      ), FALSE, TRUE);
    }


  }

  /**
   * Updates a particular model.
   * If update is successful, the browser will be redirected to the 'view' page.
   * @param integer $id the ID of the model to be updated
   */
  public function actionUpdate($id) {
    $model = $this->loadModel($id);

    // Uncomment the following line if AJAX validation is needed
    // $this->performAjaxValidation($model);

    if (isset($_POST['Category'])) {
      $model->attributes = $_POST['Category'];
      if ($model->save()) /* $this->redirect(array('view','id'=>$model->id));*/ {
        MainMenu::clearMenuCache();
        echo Yii::t('admin', "Запись сохранена");
      }
    }
    else {
      $this->renderPartial('update', array(
        'model' => $model,
      ), FALSE, TRUE);
    }


  }

  /**
   * Deletes a particular model.
   * If deletion is successful, the browser will be redirected to the 'admin' page.
   * @param integer $id the ID of the model to be deleted
   */
  public function actionDelete($id) {
    if (Yii::app()->request->isPostRequest) {
      // we only allow deletion via POST request
      $this->loadModel($id)->delete();

      // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
      if (!isset($_GET['ajax'])) {
        $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
      }
    }
    else {
      throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
    }
  }

  /**
   * Lists all models.
   */
  public function actionIndex() {
    $dataProvider = new CActiveDataProvider('Category');
    $this->renderPartial('index', array(
      'dataProvider' => $dataProvider,
    ), FALSE, TRUE);
  }

  /**
   * Manages all models.
   */
  public function actionAdmin($cid = NULL) {
    $model = new Category('search');
    $model->unsetAttributes(); // clear any default values
    $model->parent = $cid;

    if (isset($_POST['Category'])) {
      $model->attributes = $_POST['Category'];
    }
    elseif (isset($_GET['Category'])) {
      $model->attributes = $_GET['Category'];
    }
    if (!$model->onmain) {
      $model->unsetAttributes(array('onmain'));
    }
    if (!$model->status) {
      $model->unsetAttributes(array('status'));
    }
    if ($cid == NULL) {
      $tree = Category::getTree(FALSE, Utils::TransLang(), 1, 0, 2);
    }
    else {
      $tree = Category::getTree(FALSE, Utils::TransLang(), $cid, 0, 3);
    }
//      Yii::app()->clientscript->scriptMap['ds.admin.interface.js'] = false;
//      Yii::app()->clientscript->scriptMap['ds.admin.logic.js'] = false;
    $this->renderPartial('admin', array(
      'model' => $model,
      'tree' => $tree
    ), FALSE, TRUE);
  }

  /**
   * Returns the data model based on the primary key given in the GET variable.
   * If the data model is not found, an HTTP exception will be raised.
   * @param integer the ID of the model to be loaded
   */
  public function loadModel($id) {
    $model = Category::model()->findByPk($id);
    if ($model === NULL) {
      throw new CHttpException(404, 'The requested page does not exist.');
    }
    return $model;
  }

  /**
   * Performs the AJAX validation.
   * @param CModel the model to be validated
   */
  protected function performAjaxValidation($model) {
    if (isset($_POST['ajax']) && $_POST['ajax'] === 'category-form') {
      echo CActiveForm::validate($model);
      Yii::app()->end();
    }
  }
}

protected/modules/admin/views/category/_form.php
<?/*******************************************************************************************************************
* This file is the part of "DropShop" taobao(c) showcase project http://dropshop.pro
* Copyright (C) 2013 - 2014 DanVit Labs http://danvit.net
* All rights reserved and protected by law. Certificate #40514-UA 21.12.2013
* You can't use this file without of the author's permission.
* ====================================================================================================================
* <description file="_form.php">
* </description>
**********************************************************************************************************************/?>
<div class="form">

<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id'=>"category-form-$model->id",
	'enableAjaxValidation'=>false,
)); ?>

	<?php echo $form->errorSummary($model); ?>
  <div class="row">
    <?php echo $form->hiddenField($model,'cid'); ?>
  </div>

  <div class="row">
    <?php echo $form->hiddenField($model,'parent'); ?>
  </div>

  <div class="row">
    <?php echo $form->hiddenField($model,'is_parent'); ?>
  </div>

  <div class="row">
    <?php echo $form->hiddenField($model,'id'); ?>
  </div>

    <div class="row-fluid">
        <div class="span10">
            <?php echo $form->labelEx($model,'url'); ?>
            <?php echo $form->textField($model,'url', array('class'=>'span12','maxlength'=>256)); ?>
            <?php echo $form->error($model,'url'); ?>
        </div>
        <div class="span1">
            <?php echo $form->labelEx($model,'onmain'); ?>
            <?php echo $form->checkBox($model,'onmain', array('class'=>'span12')); ?>
            <?php echo $form->error($model,'onmain'); ?>
        </div>
        <div class="span1">
            <?php echo $form->labelEx($model,'status'); ?>
            <?php echo $form->checkBox($model,'status', array('class'=>'span12')); ?>
            <?php echo $form->error($model,'status'); ?>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span6">
                <div class="summary"><?=Yii::t('admin','Русский перево1д');?></div><br>
                    <?php echo $form->labelEx($model,'ru'); ?>
                    <?php echo $form->textField($model,'ru',array('class'=>'span12','maxlength'=>256)); ?>
                    <?php echo $form->error($model,'ru'); ?>

                    <?php echo $form->labelEx($model,'page_desc_ru'); ?>
                    <?php echo $form->textArea($model,'page_desc_ru',array('class'=>'span12','rows'=>5)); ?>
                    <?php echo $form->error($model,'page_desc_ru'); ?>

                    <?php echo $form->labelEx($model,'meta_desc_ru'); ?>
                    <?php echo $form->textArea($model,'meta_desc_ru',array('class'=>'span12','rows'=>5)); ?>
                    <?php echo $form->error($model,'meta_desc_ru'); ?>

                    <?php echo $form->labelEx($model,'meta_keeword_ru'); ?>
                    <?php echo $form->textArea($model,'meta_keeword_ru',array('class'=>'span12','rows'=>5)); ?>
                    <?php echo $form->error($model,'meta_keeword_ru'); ?>

                    <?php echo $form->labelEx($model,'page_title_ru'); ?>
                    <?php echo $form->textArea($model,'page_title_ru',array('class'=>'span12','rows'=>5)); ?>
                    <?php echo $form->error($model,'page_title_ru'); ?>
        </div>
        <div class="span6">
                <div class="summary"><?=Yii::t('admin','Англ. перевод');?></div><br>
                    <?php echo $form->labelEx($model,'en'); ?>
                    <?php echo $form->textField($model,'en',array('class'=>'span12','maxlength'=>256)); ?>
                    <?php echo $form->error($model,'en'); ?>

                    <?php echo $form->labelEx($model,'page_desc_en'); ?>
                    <?php echo $form->textArea($model,'page_desc_en',array('class'=>'span12','rows'=>5)); ?>
                    <?php echo $form->error($model,'page_desc_en'); ?>

                    <?php echo $form->labelEx($model,'meta_desc_en'); ?>
                    <?php echo $form->textArea($model,'meta_desc_en',array('class'=>'span12','rows'=>5)); ?>
                    <?php echo $form->error($model,'meta_desc_en'); ?>

                    <?php echo $form->labelEx($model,'meta_keeword_en'); ?>
                    <?php echo $form->textArea($model,'meta_keeword_en',array('class'=>'span12','rows'=>5)); ?>
                    <?php echo $form->error($model,'meta_keeword_en'); ?>

                    <?php echo $form->labelEx($model,'page_title_en'); ?>
                    <?php echo $form->textArea($model,'page_title_en',array('class'=>'span12','rows'=>5)); ?>
                    <?php echo $form->error($model,'page_title_en'); ?>
        </div>
    </div>






	<div class="row buttons">
      <?    $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType'=>'submit',
        //'id'=>'sub2',
        'type'=>'info',
        'icon'=>'ok white',
        'label'=>Yii::t('admin','Сохранить'),
        'htmlOptions'=>array('style'=>'float:right;margin-top:25px;','onclick'=>'saveCategory('.$model->id.'); return false;'),
      ));
      ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/modules/admin/views/category/_search.php
<?/*******************************************************************************************************************
* This file is the part of "DropShop" taobao(c) showcase project http://dropshop.pro
* Copyright (C) 2013 - 2014 DanVit Labs http://danvit.net
* All rights reserved and protected by law. Certificate #40514-UA 21.12.2013
* You can't use this file without of the author's permission.
* ====================================================================================================================
* <description file="_search.php">
* </description>
**********************************************************************************************************************/?>
<div class="form">

<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
	'id'=>"search-categories-form"
)); ?>
    <div class="row-fluid">
        <div class="span6">
            <?php echo $form->label($model,'cid'); ?>
            <?php echo $form->textField($model,'cid',array('class'=>'span12')); ?>

            <?php echo $form->label($model,'ru'); ?>
            <?php echo $form->textField($model,'ru',array('class'=>'span12')); ?>

            <?php echo $form->label($model,'onmain'); ?>
            <?php echo $form->checkBox($model,'onmain'); ?>
        </div>
        <div class="span6">
            <?php echo $form->label($model,'parent'); ?>
            <?php echo $form->textField($model,'parent',array('class'=>'span12')); ?>

            <?php echo $form->label($model,'en'); ?>
            <?php echo $form->textField($model,'en',array('class'=>'span12')); ?>

            <?php echo $form->label($model,'status'); ?>
            <?php echo $form->checkBox($model,'status'); ?>
        </div>
    </div>

        <div class="row buttons">
          <? $this->widget('bootstrap.widgets.TbButton', array(
            'buttonType'=>'submit',
            //'id'=>'sub2',
            'type'=>'info',
            'icon'=>'ok white',
            'label'=>Yii::t('admin','Поиск'),
            'htmlOptions'=>array('class'=>'btn-block','onclick'=>'searchCategories(this); return false;'),
          ));
          ?>          
        </div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/modules/admin/views/category/_view.php
<?/*******************************************************************************************************************
* This file is the part of "DropShop" taobao(c) showcase project http://dropshop.pro
* Copyright (C) 2013 - 2014 DanVit Labs http://danvit.net
* All rights reserved and protected by law. Certificate #40514-UA 21.12.2013
* You can't use this file without of the author's permission.
* ====================================================================================================================
* <description file="_view.php">
* </description>
**********************************************************************************************************************/?>
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('cid')); ?>:</b>
	<?php echo CHtml::encode($data->cid); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('ru')); ?>:</b>
	<?php echo CHtml::encode($data->ru); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('en')); ?>:</b>
	<?php echo CHtml::encode($data->en); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('parent')); ?>:</b>
	<?php echo CHtml::encode($data->parent); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('is_parent')); ?>:</b>
	<?=($data->is_parent==1) ? Yii::t('admin','Да') : Yii::t('admin','Нет')?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('onmain')); ?>:</b>
	<?=($data->onmain==1) ? Yii::t('admin','Да') : Yii::t('admin','Нет')?>
	<br />
	
	<b><?php echo CHtml::encode($data->getAttributeLabel('status')); ?>:</b>
	<?=($data->status==1) ? Yii::t('admin','Да') : Yii::t('admin','Нет')?>
	<br />

</div>

protected/modules/admin/views/category/admin.php
<?/*******************************************************************************************************************
* This file is the part of "DropShop" taobao(c) showcase project http://dropshop.pro
* Copyright (C) 2013 - 2014 DanVit Labs http://danvit.net
* All rights reserved and protected by law. Certificate #40514-UA 21.12.2013
* You can't use this file without of the author's permission.
* ====================================================================================================================
* <description file="admin.php">
* </description>
**********************************************************************************************************************/?>
<?php
$this->breadcrumbs=array(
  Yii::t('admin','Категории')=>array('index'),
  Yii::t('admin','Управление'),
);



?>

<h1><?=Yii::t('admin','Управление категориями taobao')?></h1>
<div>
  <?=Yii::t('admin','Вы можете использовать различные операторы сравнения для поиска категорий.')?> (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
  or <b>=</b>)
</div>
<div  >
  <?php $this->renderPartial('_search',array(
    'model'=>$model,
  ),false,true); ?>
</div><!-- search-form -->
<?
if ($model->parent==null) {
  $id='root';
} else {
  $id=$model->parent;
}

 $this->widget('CTreeView',
  array(
    'id'=>'category-tree-'.$id,
    'data' => $tree
  ));

?>

<?
$this->widget('bootstrap.widgets.TbGridView', array(
	'id'=>'category-grid-'.$id,
	'dataProvider'=>$model->search(),
	'filter'=>$model->search()->model,
  'type'=>'striped bordered condensed',
  'template'=>'{summary}{pager}{items}{pager}',
	'columns'=>array(
		array(
                    'name'=>'cid',
                    'type'=>'raw',
                    'value'=>'($data->is_parent==1)?
                        CHtml::link($data->cid,Yii::app()->createUrl("/admin/category/admin",array("cid"=>$data->cid)), array("onclick"=>"getContent(this,\"'.Yii::t('main','Категории от').' №$data->cid\");return false;","title"=>Yii::t("admin","Просмотр подкатегорий"))):$data->cid',
                ),
		'ru',
		'en',
                array(
                          'name'=>'onmain',
                          'class' => 'CCheckBoxColumn',
                          'checked'=>'$data->onmain==1',
                          'header'=>Yii::t('admin','На главной'),
                          //'disabled'=>'true',
                          'selectableRows'=>0,

                ),
              array(
                'name'=>'status',
                'class' => 'CCheckBoxColumn',
                'checked'=>'$data->status==1',
                'header'=>Yii::t('admin','Вкл.'),
                //'disabled'=>'true',
                'selectableRows'=>0,
                            ),
              array(
                              'type'=>'raw',
                              'value'=>'CHtml::link(Yii::t("admin","редактировать"), array("category/update", "id"=>$data->id), array("onclick"=>"getContent(this,\"'.Yii::t('main','Категория').' №$data->cid\");return false;","title"=>Yii::t("admin","Изменить параметры категории")))',
                          ),
	),
    ));  ?>

protected/modules/admin/views/category/create.php
<?/*******************************************************************************************************************
* This file is the part of "DropShop" taobao(c) showcase project http://dropshop.pro
* Copyright (C) 2013 - 2014 DanVit Labs http://danvit.net
* All rights reserved and protected by law. Certificate #40514-UA 21.12.2013
* You can't use this file without of the author's permission.
* ====================================================================================================================
* <description file="create.php">
* </description>
**********************************************************************************************************************/?>
<?php
$this->breadcrumbs=array(
  Yii::t('admin','Категории')=>array('index'),
  Yii::t('admin','Создание'),
);

$this->menu=array(
	array('label'=>'List Category', 'url'=>array('index')),
	array('label'=>'Manage Category', 'url'=>array('admin')),
);
?>

<h1>Create Category</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/admin/views/category/index.php
<?/*******************************************************************************************************************
* This file is the part of "DropShop" taobao(c) showcase project http://dropshop.pro
* Copyright (C) 2013 - 2014 DanVit Labs http://danvit.net
* All rights reserved and protected by law. Certificate #40514-UA 21.12.2013
* You can't use this file without of the author's permission.
* ====================================================================================================================
* <description file="index.php">
* </description>
**********************************************************************************************************************/?>
<?php
$this->breadcrumbs=array(
  Yii::t('admin','Категории taobao'),
);

$this->menu=array(	
	array('label'=>Yii::t('admin','Управление категориями taobao'), 'url'=>array('admin')),
);
?>

<h1>Categories</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
    'id'=>'category-listview',
    'ajaxUpdate'=>true,
)); ?>

protected/modules/admin/views/category/update.php
<?/*******************************************************************************************************************
* This file is the part of "DropShop" taobao(c) showcase project http://dropshop.pro
* Copyright (C) 2013 - 2014 DanVit Labs http://danvit.net
* All rights reserved and protected by law. Certificate #40514-UA 21.12.2013
* You can't use this file without of the author's permission.
* ====================================================================================================================
* <description file="update.php">
* </description>
**********************************************************************************************************************/?>
<?php
$this->breadcrumbs=array(
  Yii::t('admin','Категории taobao')=>array('index'),
	$model->id=>array('view','id'=>$model->id),
  Yii::t('admin','Управление'),
);

$this->menu=array(
	array('label'=>Yii::t('admin','Список категорий'), 'url'=>array('index')),
	array('label'=>Yii::t('admin','Просмотр категории'), 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>Yii::t('admin','Управление категориями'), 'url'=>array('admin')),
);
?>

<h1><?=Yii::t('admin','Изменение категории taobao')?> <strong style="color:#0093f5;">#<?php echo $model->ru; ?></strong></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/admin/views/category/view.php
<?/*******************************************************************************************************************
* This file is the part of "DropShop" taobao(c) showcase project http://dropshop.pro
* Copyright (C) 2013 - 2014 DanVit Labs http://danvit.net
* All rights reserved and protected by law. Certificate #40514-UA 21.12.2013
* You can't use this file without of the author's permission.
* ====================================================================================================================
* <description file="view.php">
* </description>
**********************************************************************************************************************/?>
<?php
$this->breadcrumbs=array(
  Yii::t('admin','Категории')=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>Yii::t('admin','Список категорий'), 'url'=>array('index')),
	array('label'=>Yii::t('admin','Управление категориями'), 'url'=>array('admin')),
);
?>

<h1>Просмотр категории #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
                'id',
		'cid',
		'ru',
		'en',
		'parent',
                array(
                    'name' => 'is_parent',
                    'type'=>'raw',
                    'value'=>($model->is_parent==1)?Yii::t('admin',"Да"):Yii::t('admin',"Нет"),
                ),
		array(
                    'name' => 'onmain',
                    'type'=>'raw',
                    'value'=>($model->onmain==1)?Yii::t('admin',"Да"):Yii::t('admin',"Нет"),
                ),
		array(
                    'name' => 'status',
                    'type'=>'raw',
                    'value'=>($model->status==1)?Yii::t('admin',"Да"):Yii::t('admin',"Нет"),
                ),		
	),
)); ?>